import Image from 'next/image';
import { products } from '@/constants/products';
import { ProductCard } from './ProductCard';
import { Reveal } from './Reveal';
import { Heart, Recycle, Sprout, ShieldCheck } from 'lucide-react';

export function Products(){return <section id="products" className="container-pad py-20"><div className="mx-auto max-w-7xl"><Reveal><p className="text-center font-bold uppercase tracking-[.3em] text-leaf">Our Rituals</p><h2 className="mt-3 text-center font-serif text-5xl font-bold">Choose Your Daily Glow</h2></Reveal><div className="mt-12 grid gap-6 md:grid-cols-3">{products.map((p,i)=><ProductCard key={p.id} product={p} index={i}/>)}</div></div></section>}

export function Ritual(){return <section id="ritual" className="container-pad py-20"><div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-2"><Reveal><Image src="/images/package-back.jpeg" alt="Earthiva package back side" width={1200} height={800} className="rounded-[2rem] shadow-soft"/></Reveal><Reveal delay={.15}><p className="font-bold uppercase tracking-[.3em] text-clay">How to use</p><h2 className="mt-3 font-serif text-5xl font-bold">Simple DIY Ritual</h2><div className="mt-8 space-y-5 text-lg text-ink/75"><p><b>1.</b> Take 1–2 tbsp powder.</p><p><b>2.</b> Mix with rose water, curd, honey, aloe vera or plain water.</p><p><b>3.</b> Apply on face, body or hair.</p><p><b>4.</b> Leave for 10–15 minutes and rinse naturally.</p></div><p className="mt-8 rounded-3xl bg-card p-5 text-sm text-ink/70">For external use only. Patch test before use. Results may vary depending on skin type.</p></Reveal></div></section>}

export function Why(){const items=[['Pure Ingredients',Sprout],['Skin-safe Rituals',ShieldCheck],['Made with Love',Heart],['Sustainable Packaging',Recycle]];return <section id="why-earthiva" className="container-pad py-20"><div className="mx-auto max-w-7xl rounded-[2.5rem] bg-leaf p-8 text-cream shadow-soft md:p-14"><Reveal><h2 className="font-serif text-5xl font-bold">Why Earthiva?</h2><p className="mt-5 max-w-3xl text-lg text-cream/80">A premium natural-care brand built around transparency, simple ingredients, beautiful rituals, and Amazon-first customer trust.</p></Reveal><div className="mt-10 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{items.map(([text,Icon])=><div key={text as string} className="rounded-3xl bg-white/10 p-6"><Icon size={34}/><h3 className="mt-5 text-xl font-bold">{text as string}</h3></div>)}</div></div></section>}

export function Contact(){return <section id="contact" className="container-pad py-20"><div className="mx-auto max-w-4xl text-center"><Reveal><h2 className="font-serif text-5xl font-bold">Ready to Launch Online?</h2><p className="mt-5 text-lg text-ink/70">Add Amazon links, WhatsApp enquiry, Instagram, Google Analytics and SEO pages to make this a trust-building brand website.</p><a href="mailto:hello@earthiva.in" className="mt-8 inline-flex rounded-full bg-clay px-8 py-4 font-bold text-white shadow-soft hover:bg-ink">Contact Earthiva</a></Reveal></div></section>}
